site_name: lernOS Digitale Zusammenarbeit Leitfaden
site_url: https://magnus-rode.github.io/
docs_dir: src
site_dir: ../docs/de

nav:
    - Willkommen: index.md
    - Über lernOS: 1-0-Ueber-lernOS.md    
    - Making of: 1-1-Making-of.md
    - Einführung: 
      - Lernpfad: 2-0-Einfuehrung.md
      - Warum digitale Zusammenarbeit?: 2-1-Warum.md
      - Was sind digitale Kollaborationstools?: 2-2-Kollaborationstools.md
      - Was gehört alles zur digitalen Zusammenarbeit?: 2-3-Bereiche.md
    - Deine Lernreise im Überblick: 3-0-Lernreise.md
    - Lernpfad: 
      - Woche 0: 4-0-Woche-0.md
      - Woche 1: 4-1-Woche-1.md
      - Woche 2: 4-2-Woche-2.md
      - Woche 3: 4-3-Woche-3.md
      - Woche 4: 4-4-Woche-4.md
      - Woche 5: 4-5-Woche-5.md
      - Woche 6: 4-6-Woche-6.md
      - Woche 7: 4-7-Woche-7.md
      - Woche 8: 4-8-Woche-8.md
      - Woche 9: 4-9-Woche-9.md
      - Woche 10: 4-10-Woche-10.md
      - Woche 11: 4-11-Woche-11.md
      - Woche 12: 4-12-Woche-12.md
    - Kata-log: 
      - Kata 0: 5-0-Kata-0.md
      - Kata 1: 5-1-Kata-1.md
      - Kata 2: 5-2-Kata-2.md
      - Kata 3: 5-3-Kata-3.md
      - Kata 4: 5-4-Kata-4.md
      - Kata 5: 5-5-Kata-5.md
      - Kata 6: 5-6-Kata-6.md
      - Kata 7: 5-7-Kata-7.md
      - Kata 8: 5-8-Kata-8.md
      - Kata 9: 5-9-Kata-9.md
      - Kata 10: 5-10-Kata-10.md
      - Kata 11: 5-11-Kata-11.md
      - Kata 12: 5-12-Kata-12.md
    - Hintergrund-Wissen: 
      - Theorie Kommunikation: 6-1-Theorie-Kommunikation.md
      - Theorie Wissen teilen: 6-2-Theorie-Wissen-teilen.md
      - Theorie Zusammenarbeit: 6-3-Theorie-Zusammenarbeit.md
      - Theorie Retrospektive: 6-4-Theorie-Retrospektive.md    
    - Vorlagen: 7-0-Vorlagen.md
    - Abschluss: 8-0-Abschluss.md
    - Anhang: _Anhang.md
    - Download:
      - PDF-Version: https://github.com/Magnus-Rode/lernos-digitale-zusammenarbeit/blob/master/de/lernOS-digitaleZusammenarbeit-Leitfaden-de_0.3.pdf
      - Word-Version: https://github.com/Magnus-Rode/lernos-digitale-zusammenarbeit/blob/master/de/lernOS-digitaleZusammenarbeit-Leitfaden-de_0.3.docx
      - HTML-Version: https://github.com/Magnus-Rode/lernos-digitale-zusammenarbeit/blob/master/de/lernOS-digitaleZusammenarbeit-Leitfaden-de_0.3.html
      - E-Book (epub): https://github.com/Magnus-Rode/lernos-digitale-zusammenarbeit/blob/master/de/lernOS-digitaleZusammenarbeit-Leitfaden-de_0.3.epub
      - E-Book (mobi): https://github.com/Magnus-Rode/lernos-digitale-zusammenarbeit/blob/master/de/lernOS-digitaleZusammenarbeit-Leitfaden-de_0.3.mobi
      - Canvas: https://github.com/Magnus-Rode/lernos-digitale-zusammenarbeit/blob/master/de/Vorlagen/Collaboration%20Canvas%20(lernOS%20Digitale%20Zusammenarbeit).pptx
    - Links:
      - lernos.org: https://lernos.org
      - CONNECT Community: https://community.cogneon.de
      - Peerfinder: https://web.peerfinder.app

theme:
    name: 'material'
    custom_dir: src/overrides
    palette:
        scheme: lernos
    language: de
    icon:
      logo: material/home
      repo: fontawesome/brands/github

extra_css:
  - stylesheets/extra.css

repo_name: 'magnus-rode/lernos-digitale-zusammenarbeit'
repo_url: 'https://github.com/Magnus-Rode/lernos-digitale-zusammenarbeit'

extra:
    social:
        - icon: fontawesome/brands/twitter
          link: 'https://twitter.com/lern_os'
        - icon: fontawesome/brands/linkedin
          link: 'https://www.linkedin.com/showcase/lern-os'
        - icon: fontawesome/brands/github
          link: 'https://github.com/cogneon'
    disqus: lernos
    analytics:
       provider: custom

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search
