site_name: lernOS Leitfaden Digitale Zusammenarbeit
site_url: https://cogneon.github.io/
docs_dir: src
site_dir: ../docs/de
edit_uri: 'edit/master/de/src'

nav:
    - Willkommen:
      - Lernpfad: 3-01-Einfuehrung.md
      - Warum digitale Zusammenarbeit?: 3-02-Warum.md
      - Was sind digitale Kollaborationstools?: 3-03-Kollaborationstools.md
      - Was gehört alles zur digitalen Zusammenarbeit?: 3-04-Bereiche.md
      - Über lernOS: 3-05-Ueber-lernOS.md       
    - Lernpfad: 
      - Deine Lernreise im Überblick: 4-01-Ueberblick.md
      - Vorbereitungstreffen: 4-02-Vorbereitungstreffen.md
      - Kata 1: 4-03-Kata-1.md
      - Kata 2: 4-04-Kata-2.md
      - Kata 3: 4-05-Kata-3.md
      - Kata 4: 4-06-Kata-4.md
      - Kata 5: 4-07-Kata-5.md
      - Kata 6: 4-08-Kata-6.md
      - Kata 7: 4-09-Kata-7.md
      - Kata 8: 4-10-Kata-8.md
      - Kata 9: 4-11-Kata-9.md
      - Kata 10: 4-12-Kata-10.md
      - Kata 11: 4-13-Kata-11.md
      - Kata 12: 4-14-Kata-12.md
      - Abschluss: 4-15-Abschluss.md
    - Grundlagen (Theorie):
      - Theorie Grundlagen der Zusammenarbeit: 5-01-Theorie-Grundlagen-der-Zusammenarbeit.md
      - Theorie Kommunikation: 5-02-Theorie-Kommunikation.md
      - Theorie Retrospektive: 5-03-Theorie-Retrospektive.md
      - Theorie Meetings: 5-04-Theorie-Meetings.md
      - Theorie Entscheidungen: 5-05-Theorie-Entscheidungen.md
      - Theorie Wissen: 5-06-Theorie-Wissen.md
    - Anhang:
      - Vorlagen: 6-01-Vorlagen.md
      - Making of: 6-02-Making-of.md
      - Kontakt: 6-03-Kontakt.md
    - Download:
      - PDF-Version: https://github.com/cogneon/lernos-digitale-zusammenarbeit/blob/master/de/lernOS-Digitale-Zusammenarbeit-Leitfaden-2.0.pdf
      - Word-Version: https://github.com/cogneon/lernos-digitale-zusammenarbeit/raw/refs/heads/master/de/lernOS-Digitale-Zusammenarbeit-Leitfaden-2.0.docx
      - E-Book (epub): https://github.com/cogneon/lernos-digitale-zusammenarbeit/raw/refs/heads/master/de/lernOS-Leitfaden-Digitale-Zusammenarbeit-2.0.epub
      - Canvas: https://github.com/cogneon/lernos-digitale-zusammenarbeit/raw/refs/heads/master/de/Vorlagen/Collaboration%20Canvas%20(lernOS%20Digitale%20Zusammenarbeit).pptx
    - Links:
      - lernos.org: https://lernos.org
      - CONNECT Community: https://community.cogneon.de
      - Peerfinder: https://web.peerfinder.app

theme:
    name: 'material'
    custom_dir: src/overrides
    palette:
        scheme: lernos
    language: de
    icon:
      logo: material/home
      repo: fontawesome/brands/github
    features:
      - toc.integrate
      - search.share
      - navigation.top
      - navigation.footer

extra_css:
  - stylesheets/extra.css

repo_name: 'cogneon/lernos-digitale-zusammenarbeit'
repo_url: 'https://github.com/cogneon/lernos-digitale-zusammenarbeit'

extra:
    social:
        - icon: fontawesome/brands/mastodon
          link: 'https://colearn.social/@lernos'
        - icon: fontawesome/brands/linkedin
          link: 'https://www.linkedin.com/showcase/lern-os'
        - icon: fontawesome/brands/github
          link: 'https://github.com/cogneon'
    giscus: true
    analytics:
       provider: custom
    alternate:
         - name: English
           link: https://cogneon.github.io/lernos-digitale-zusammenarbeit/en
           lang: en
    generator: false

markdown_extensions:
  - footnotes
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search

copyright: <a href="https://cogneon.github.io/lernos-digitale-zusammenarbeit/de/3-05-Ueber-lernOS/">CC BY 4.0</a> - <a href="https://cogneon.github.io/lernos-digitale-zusammenarbeit/de/6-03-Kontakt/">Kontakt</a>

